RocketChat/developer-docs

api/rest-api/methods/apps-endpoints/whatsapp-endpoints/template-message.md

Add a warning to add a `+`(plus) in front of all phone numbers on Whatsapp template endpoint

Add a warning for WhatsApp number in the rest endpoint

---

api/rest-api/methods/roles/create.md
api/rest-api/methods/roles/update.md

Documentation for the changes made in https://github.com/RocketChat/Rocket.Chat/pull/22279.

Add documentation for the new `roles.update` endpoint

---

api/rest-api/README.md
api/rest-api/endpoints/roles/README.md
api/rest-api/endpoints/roles/delete.md
api/rest-api/endpoints/roles/update.md

Adding documentation for the new `roles.delete` endpoint and update some other `roles` endpoints that were incorrect.
Relatated to https://github.com/RocketChat/Rocket.Chat/pull/22497

Update `roles` endpoint documentation

---

SUMMARY.md
api/rest-api/endpoints/team-collaboration-endpoints/README.md
api/rest-api/endpoints/team-collaboration-endpoints/im-endpoints/create.md
api/rest-api/endpoints/team-collaboration-endpoints/im-endpoints/delete.md
api/rest-api/endpoints/team-collaboration/README.md
guides/developer/possible-error.md

**Added in version:** 
3.18.0 https://github.com/RocketChat/Rocket.Chat/releases/tag/3.18.0-rc.0
**Type of feature:** 
REST API
**Involved settings:** 
N/A
**Description:**
Add documentation for new IM delete REST endpoint
Update documentation for IM create REST endpoint `excludeSelf` option
See https://github.com/RocketChat/Rocket.Chat/pull/18022
Also removed various zero-width space characters
**How to use this feature:**
Change is well documented in the create.md and delete.md files

[Fix] Update documentation for IM REST endpoint changes

---

getting-started/choosing-a-development-host/mac-osx.md

setting developer environment in m1  macos

Updated  Docs for Mac OSX

---

rocket.chat/rocket.chat-server/windows-10.md

1) updated apt-get tools
2) added importance about /home/username dir usage

Update windows-10.md: apt-get libraries and ~ info

---

apps-engine/fundamentals-of-apps/scheduler-api.md

There might be chances that many developers will face issues while scheduling jobs inside the app engine. These new changes inside the document will help them to better understand how to pass custom data inside the processor function.

Clean Explanation Of Processor Function Arguments.

---

apps-engine/fundamentals-of-apps/uikit/opening-the-contextual-bar.md

fix a minor typo in fundamentals-of-apps docs

[FIX] typo in fundamentals-of-apps

---

rocket.chat/rocket.chat-server/gitpod.md
rocket.chat/rocket.chat-server/linux.md

This PR updates the Rocket Chat Gitpod snd Linux Environment setup developer docs.
Thank you!

Environment setup docs update

---

rocket.chat/contribute-to-rocket.chat/contribute-to-rocket.chat-faqs.md

I have added some of the frequently asked questions and their possible answers related to contributing to Rocket.Chat. These can be added to the documentation for common FAQs.

Added few common FAQs for Rocket.Chat

---

.github/ISSUE_TEMPLATE.md

created issue template

---

rocket.chat/rocket.chat-server/windows-10.md

Update the version of meteor node and meteor npm after installing meteor

Update version of meteor node and npm version

---

rocket.chat/rocket.chat-server/linux.md
rocket.chat/rocket.chat-server/windows-10.md

Add information manage node version in WSL setup

---

rocket.chat/rocket-chat-environment-setup/linux.md

Fix : #139 Update rocket-chat-environment-setup/linux.md

---

rocket.chat/rocket-chat-environment-setup/linux.md

Corrected typo in developer installation docs.

---

mobile-app/testing-your-mobile-app.md

Fix typo in "Testing your mobile app" section: "yarn prettier-lint"

---

reference/api/rest-api/endpoints/core-endpoints/assets-endpoints/setasset.md

Previous example and documentation did not reflect how the source code works. We need to set the asset to the file and assetName to the type of asset.

Updates setasset.md with a working example

---

reference/api/realtime-api/subscriptions/stream-notify-room.md

user-activity is the only way to know if the user is typing or not.

Added user-activity to docs

---

reference/api/realtime-api/method-calls/notify-room-stream.md

Update notify-room-stream.md to reflect user-activity method

Added user-activity method to docs

---

rocket.chat/contribute-to-rocket.chat/contribute-to-rocket.chat-faqs.md

Includes helpful links and detailed language to FAQ in order to better guide newcomers to the project

Update Documentation: Contribute to Rocket.Chat FAQs

---

open-source-projects/server/server-environment-setup/windows-10.md

Closes : https://github.com/RocketChat/Rocket.Chat/issues/29732

Update Documentation: Update minimum required node version from 14.19.3 to 14.21.3 in docs

---

reference/api/rest-api/endpoints/messaging/chat-endpoints/getthreadmessages.md

Updates to [Get Thread Messages](https://developer.rocket.chat/reference/api/rest-api/endpoints/messaging/chat-endpoints/getthreadmessages) Commit 3175b94 closes #194 and commit efa2355 closes #195. Please let me know if you'd prefer to separate pull requests.
Also, are example message results preferred without the `md` field?

Update GetThreadMessages parameters and example

---

open-source-projects/server/repository-structure.md

Fixed typo in /open-source-projects/server/repository-structure

fix: fixed typo in /open-source-projects/server/repository-structure

---

customize-and-embed/white-labeling/customizing-colors.md

The current documentation doesn't mention how to actually change variables listed under `Variables List` in [Customizing Colors](https://developer.rocket.chat/customize-and-embed/white-labeling/customizing-colors). Added a section that explains how to do it.
Fixes RocketChat/Rocket.Chat#30621

Explain how to overwrite default variables
